var print_text = {
    // ------------------------ GENERAL
    "GENERAL_UPDATE_SUCCESS": "Dữ liệu cập nhật thành công!",
    "GENERAL_FEATURE_IN_DEVELOPMENT": "Tính năng đang phát triển, vui lòng thử lại sau!",
    // ------------------------ GROUPVIEW
    "GROUPVIEW_POSITION":"Vị trí hiện tại:  ",
    "GROUPVIEW_TITLE":"Tìm kiếm / Danh sách địa điểm",
	"SEARCH_PLACEHOLDER" :"Tìm kiếm địa điểm",
	"GROUPVIEW_SEARCH_NO_RESULT": "Không có kết quả được tìm thấy!",
    // ------------------------ AUDIO_GROUP
    "AUDIO_GROUP_TITLE":"Khám phá thông tin",
    "AUDIO_GROUP_CURRENT":"Nhóm Cảnh hiện tại",
    "AUDIO_GROUP_MORE":"Danh sách",
    "AUDIO_GROUP_EXPLORE":"Các địa điểm khác",
    "AUDIO_GROUP_EXPLORE_SCENE":"Xem các Cảnh trong Nhóm này",
    "AUDIO_GROUP_GO_NEXT_GROUP":"Đến nhóm cảnh tiếp theo",
    "AUDIO_GROUP_VIEW_INFO_TITLE": "Thông tinh Cảnh hiện tại",
    "AUDIO_GROUP_DATA_MISSING": "Không có thông tin được tìm thấy!",
    // ------------------------ MATERIAL
    "MATERIAL_TITLE": "Tư liệu",
    "MATERIAL_DATA_MISSING":"Dữ liệu đang được cập nhật!",
    "MATERIAL_SEARCH": "Tìm kiếm",
    "MATERIAL_SEARCH_COUNT": "Kết quả tìm kiếm",
    "MATERIAL_VIDEO": "Video",
    "MATERIAL_DOCUMENT": "Tư liệu",
    "MATERIAL_ALBUM": "Album Ảnh",
    "MATERIAL_MODEL": "Hiện vật 3D",
    // ------------------------ GALLERY
    "GALLERY_TITLE": "Thư viện 3D",
    "GALLERY_DATA_MISSING": "Dữ liệu Hiện vật đang được cập nhật!",
    "GALLERY_SHARE": "Chia sẻ",
    "GALLERY_SEEMORE": "Xem thông tin",
    "GALLERY_MODEL_SHARE": "Chia sẻ hiện vật",
    "GALLERY_VOICE": "Thuyết minh tự động",
    "GALLERY_ROTATE": "Xoay tự động",
    "GALLERY_HDR": "Đổi hình nền HDR",
    "GALLERY_DESCRIPTION": "Mô tả",
    "GALLERY_POST": "Bài viết",
    "GALLERY_IMAGE": "Hình ảnh",
    "GALLERY_VIDEO": "Video",
    // ------------------------ AUTOTOUR
    "AUTOTOUR_TITLE": "Tour tự động",
    "AUTOTOUR_DATA_MISSING": "Tours không có dữ liệu!",
    "AUTOTOUR_TOUR_START": "Bắt đầu tour",
    "AUTOTOUR_TOUR_ROUTE":"Xem lộ trình",
    "AUTOTOUR_DESTINATION": "điểm đến",
    "AUTOTOUR_TOUR_START_FROM": "Bắt đầu tour từ đây?",
    "AUTOTOUR_TOUR_START_FROM_ACCEPT": "Có",
    "AUTOTOUR_TOUR_START_FROM_DECLINE": "Huỷ",
    // ------------------------ SETTINGS
    "SETTINGS_TITLE": "Cài đặt",
    "SETTINGS_ROTATE": "Tự động xoay 360",
    "SETTINGS_HOTSPOT": "Điều hướng 3D",
    "SETTINGS_SOUND": "Âm thanh",
    "SETTINGS_FULLSCREEN": "Toàn màn hình",
    "SETTINGS_LANGUAGE_SELECT": "Chọn ngôn ngữ",
    "SETTINGS_VRMODE": "Chế độ VR",
    "SETTINGS_EXIT_VRMODE": "Thát chế độ VR",
    "SETTINGS_PLANET": "Chế độ Hành tinh nhỏ",
    "SETTINGS_EXIT_PLANET": "Thoát chế độ Hành tinh nhỏ",
    "SETTINGS_PANNINI": "Chế độ Góc nhìn rộng",
    "SETTINGS_EXIT_PANNINI": "Thoát chế độ Góc nhìn rộng",
    "SETTINGS_GUIDE": "Hướng dẫn sử dụng",
    "SETTINGS_GUIDE_TITLE_LEFT": "Nút tác vụ bên trái",
    "SETTINGS_GUIDE_FIND": "Tìm kiếm",
    "SETTINGS_GUIDE_MAP": "Xem bản đồ",
    "SETTINGS_GUIDE_TOUR": "Tham quan tự động",
    "SETTINGS_GUIDE_GALLERY": "Thư viện 3D",
    "SETTINGS_GUIDE_MATERIAL": "Kho tư liệu",
    "SETTINGS_GUIDE_GROUP_VIEW": "Thông tin nhóm cảnh",
    "SETTINGS_GUIDE_SETTING": "Cài đặt",
    "SETTINGS_GUIDE_TITLE_RIGHT": "Nút tác vụ bên phải",
    "SETTINGS_GUIDE_INFO_VIEW": "Thông tin cảnh hiện tại",
    "SETTINGS_GUIDE_SHARE": "Chia sẻ",
    "SETTINGS_GUIDE_TITLE_BOTTOM": "Thanh điều hướng bên dưới",
    "SETTINGS_GUIDE_HOME": "Trở về cảnh đầu tiên",
    "SETTINGS_GUIDE_SCENE_NAVIGATE": "Chuyển cảnh kế tiếp",
    "SETTINGS_GUIDE_SCENE_REWIND": "Quay lại cảnh vừa xem",
    "SETTINGS_CACHE": "Xoá Cache & Khởi động lại",
    // ------------------------ SHARE
    "SHARE_SUCCESS": "Thực thi thành công!",
    "SHARE_UNSUPPORTED": "Trình duyệt không hỗ trợ hành động này!",
    "SHARE_THIS_SCENE": "Chia sẻ Cảnh này",
    "SHARE_THIS_POST": "Chia sẻ Bài viết này",
    "SHARE_THIS_MODEL": "Chia sẻ Hiện vật này",
    "SHARE_THIS_MATERAIL": "Chia sẻ Tư liệu này",
    "SHARE_THIS_TOUR": "Chia sẻ Tour tự động này",
    "SHARE_COPY_QR": "Sao chép mã QR",
    "SHARE_DOWNLOAD_QR": "Tải mã QR",
    "SHARE_COPY_LINK": "Sao chép link",
    "SHARE_FROM_NETWORK": "Trên mạng xã hội",
    // ------------------------ MAP
    "MAP_TITLE": "Bản đồ",
    "MAP_MINI": "Bản đồ nội khu",
    "MAP_GOOGLE": "Google Map",
    "MAP_BACK": "Quay lại",
    "MAP_DATA_MISSING":"Bản đồ không có dữ liệu!",
    // ------------------------ LOADING (local path /hcmverse_hcm202/)
    "LOADING_START_TOUR": "Bắt đầu tham quan",
    "smart-tourism-3d": "DU LỊCH THÔNG MINH 3D/360",
    "hcmverse_hcm202": "DU LỊCH THÔNG MINH 3D/360"

}